export const resto = [
  {
    imageSrc: "https://placekitten.com/300/300",
    restaurantName: "Lool",
    restaurantDescription: "Description 1",
    lastUpdated: "Last updated 3 mins ago",
    restaurantHour: true,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Lool",
    restaurantDescription: "Description 2",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Lool",
    restaurantDescription: "Description 3",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Lool",
    restaurantDescription: "Description 4",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Restaurant 5",
    restaurantDescription: "Description 5",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Restaurant 6",
    restaurantDescription: "Description 6",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Restaurant 7",
    restaurantDescription: "Description 7",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Restaurant 8",
    restaurantDescription: "Description 8",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
  {
    imageSrc: "https://placekitten.com/300/301",
    restaurantName: "Restaurant 9",
    restaurantDescription: "Description 9",
    lastUpdated: "Last updated 5 mins ago",
    restaurantHour: false,
  },
];
